"""Created user_linkedin_info and linkedin_profiles

Revision ID: 11795bd2dd53
Revises: 2c8946b11c73
Create Date: 2025-11-07 16:58:36.625898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11795bd2dd53'
down_revision: Union[str, Sequence[str], None] = '2c8946b11c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_profile',
    sa.Column('profile_url', sa.String(length=512), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('profile_url')
    )
    op.create_table('user_linkedin_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_profile_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'linkedin_profile_url', name='user_linkedin_profile_unique')
    )
    op.create_index('idx_user_linkedin_profile_user_id', 'user_linkedin_profile', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_linkedin_profile_user_id', table_name='user_linkedin_profile')
    op.drop_table('user_linkedin_profile')
    op.drop_table('linkedin_profile')
    # ### end Alembic commands ###
